#!/Users/rafalkesik/.nvm/versions/node/v22.4.0/bin/node

let fs = require("fs");
let Phrase = require("rafalkesik-palindrome");
fs.writeFileSync("palindromes.txt", "");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
        console.log("palindrome detected:", line);
        fs.appendFile("palindromes.txt", line + "\n", function (err) {
            if (err) {
                console.log(err);
            } else {
                console.log("Added to a file");
            }
        });
    }
});